### ISSUE TITLE
Compatibility with yaml-0.8.32 package

### ISSUE THREAD

**Issue by 4e6** [commercialhaskell/lts-haskell#150]
## Issue

I'm having troubles loading some of the yaml files with `stackage-curator` built with the `yaml-0.8.32`

## Description

Package [yaml-0.8.32](https://hackage.haskell.org/package/yaml-0.9.0/changelog) adds:

- Support hexadecimal and octal number values https://github.com/snoyberg/yaml/issues/135

With this patch, some of the yaml files in this repo became invalid. 

For example, trying to load `lts-12.2` with `stackage-curator` built with yaml-0.8.32, I'm getting the error:

> Failed to parse stackage build plan: AesonException "Error in $.packages['enum-subset-generate']['github-pings'][0]: expected Text, encountered Number"

because in the package `packages.enum-subset-generate.github-pings[0]`, value `0xd34df00d` is a hexadecimal integer.

```
  enum-subset-generate:
    users:
    - enum-subset-generate
    constraints:
      benches: expect-success
      library-profiling: true
      flags: {}
      build-benchmarks: true
      non-parallel-build: false
      skip-build: false
      tests: expect-success
      haddocks: expect-success
      hide: false
      maintainer: Georg Rudoy <0xd34df00d@gmail.com> @0xd34df00d
      configure-args: []
      version-range: ! '>=0.1.0.0 && <0.2'
    version: '0.1.0.0'
    cabal-file-info:
      size: 1648
      hashes:
        MD5: 9220fdc3a64b13fe2d400c87c39955ba
        Skein512_512: 45eae774b7fe82d2b7c6a982b1482fe88ac84a020484941035a7271dceb2a0ad2b159adab8feb1befc3a2d9ff9e6fe3bc98880630a74e16db61a725005659799
        SHA1: 4cf9ce79be24ffee73843dac80d75d6fa2801d66
        SHA512: f1f425129ea930b0935be38c148dbfc638444ec494c5d1271a249c62a00072e0a0c839b8b93585616e36ec15485ca53cdffa3c9e1d8b82e3b5226b998e7585c1
        SHA256: c55480a639978f6ef47ae861d9feb5db1fadfa0b0b05c26739ab7e43f2be42fe
        GitSHA1: 40bcc72ab5fd202a657a9307b11270b48b61ad95
    simple-build: true
    github-pings:
    - 0xd34df00d          
```

`yaml-0.8.32` adds proper quotations in this case, but file `lts-12.2.yaml` was produced with the earlier version of `yaml` package and lacks the quotes.

Nightly repo might be affected too.
