### ISSUE TITLE
Add captcha-core, captcha-2captcha, and captcha-capmonster

### ISSUE THREAD

**Issue by qwbarch** [commercialhaskell/lts-haskell#330]
Checklist for adding a package:

- [ ] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Similar to <https://github.com/commercialhaskell/stackage/pull/6389>, I am able to build my packages against ``stack-nightly-2022-01-06``, but the above checks fail due to requiring a dependency not on stackage.  
Please let me know what I can do to fix this, and I'll get to it immediately

**Comment by juhp** [comment]
You need to mention the missing deps, just like you did for Nightly

**Comment by juhp** [comment]
For the next Stackage curator, these are the lines I had prepared in constraints.yaml:
```yaml
  captcha-core:
    maintainers:
    - Edward Yang @qwbarch
    source:
      revisions: use-revisions
      type: hackage
  captcha-2captcha:
    maintainers:
    - Edward Yang @qwbarch
    source:
      revisions: use-revisions
      type: hackage
  captcha-capmonster:
    maintainers:
    - Edward Yang @qwbarch
    source:
      revisions: use-revisions
      type: hackage
```
